# Default values for csr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

username: # put your name here
csr_path: secrets/my.csr # file path to certificate signing request
